version: 5.1.0
variant: default
logo: /img/author.png
head:
    favicon: /img/author.png
    manifest:
        name: 
        short_name: 
        start_url: 
        theme_color: 
        background_color: 
        display: standalone
        icons:
            -
                src: ''
                sizes: ''
                type: 
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        publisher: 
        publisher_logo: 
        image: 
    meta:
        - ''
    rss: 
navbar:
    menu:
        首页: /
        归档: /archives
        分类: /categories
        标签: /tags
    links:
        GitHub:
            icon: fab fa-github
            url: https://github.com/qianduanzhou
footer:
    links:
        GitHub:
            icon: fab fa-github
            url: https://github.com/qianduanzhou
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: true
    update_time: true
search:
    type: insight
sidebar:
    left:
        sticky: true
    right:
        sticky: true
widgets:
    -
        position: left
        type: profile
        author: zhb
        author_title: 前端程序猿
        location: 广州
        avatar: /img/author.png
        avatar_rounded: true
        gravatar: 
        follow_link: https://github.com/qianduanzhou
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/qianduanzhou
    -
        position: right
        type: toc
        index: true
        collapsed: true
        depth: 3
    -
        position: right
        type: recent_posts
    -
        position: left
        type: categories
    -
        position: left
        type: tags
    -
        position: left
        type: archives
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id: 
    bing_webmaster:
        tracking_id: 
    busuanzi: false
    cnzz:
        id: 
        web_id: 
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-left
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id: 
    hotjar:
        site_id: 
    katex: false
    mathjax: false
    outdated_browser: false
    progressbar: true
    statcounter:
        project: 
        security: 
    twitter_conversion_tracking:
        pixel_id: 
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
